#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

 
# This will only work in zsh, which maintains a $path array that maps to the
# $PATH string automatically.
path=(
    "$HOME/.local/bin"
    "/Library/TeX/texbin"
    "/usr/local/bin"
    "/usr/local/sbin"
    "/usr/bin"
    "/usr/sbin"
    "/bin"
    "/sbin"
    "$HOME/.rvm/bin"    # for RVM scripting
)

export PATH="$PATH:$HOME/.rvm/bin" 

# Include local man files:
export MANPATH="$HOME/include/man:$HOME/include/share/man:$MANPATH"

# Use vim whenever possible:
export EDITOR=vim

