#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Disable corrections (I'm not a fan, I guess):
unsetopt CORRECT

# Fixes a bug where, with RVM, `RVM_PROJECT_PATH` shows up as the path.
unsetopt auto_name_dirs

# If this is a tmux shell, load tmux-specific functions.
if [ -n "$TMUX" ]; then
    source ~/.tmux/functions
else
    source ~/.local/bin/tmux-sessions-header
fi


# EMW-defined aliases:
alias tmux='tmux -2' # force tmux to use 256-colors
alias ta='tmux attach -t'
alias dl="ls -t ~/Downloads | head -n 1 | sed -e 's:^:'"$HOME"'/Downloads/:'" # latest download
alias ql='qlmanage -p 2>/dev/null'
type nvim &>/dev/null && alias vim='nvim'

# Do not be disturbed by Ctrl-S ctrl-Q in terminals:
stty sane

# Load slow, bloated, indispensible language and integration tools. Ones I use
# rarely are off by default and can be loaded with the `use_` functions below:
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export NVM_DIR="$HOME/.nvm"
function use_nvm { [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" }
function use_gvm { [[ -s "$HOME/.gvm/bin/gvm-init.sh" ]] && source "$HOME/.gvm/bin/gvm-init.sh" }

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
if which swiftenv > /dev/null; then eval "$(swiftenv init -)"; fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
